build:
  system_packages:
    - "ffmpeg"
  python_packages:
    - "ffmpeg-python==0.2.0"
    - "ffmpeg==1.4"
    - "transformers==4.33.0"
    - "accelerate==0.34.2"
    - "torch==2.4.1"
    - "huggingface-hub==0.25.2"
